name: firebase_app_installations_platform_interface
description: A common platform interface for the firebase_app_installations plugin.
version: 0.1.4+63-a
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_app_installations/firebase_app_installations_platform_interface
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_app_installations/firebase_app_installations_platform_interface

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals:
#    path: ../../_flutterfire_internals
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/_flutterfire_internals
      ref: SwineTech/bom_4.5.0

  firebase_core:
#    path: ../../firebase_core/firebase_core
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: SwineTech/bom_4.5.0
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface:
#    path: ../../firebase_core/firebase_core_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: SwineTech/bom_4.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
