name: firebase_analytics
description:
  Flutter plugin for Google Analytics for Firebase, an app measurement
  solution that provides insight on app usage and user engagement on Android and iOS.
homepage: https://firebase.google.com/docs/analytics
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_analytics/firebase_analytics
version: 12.0.4-a
topics:
  - firebase
  - analytics
  - measure
  - insights

false_secrets:
  - example/**

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_analytics_platform_interface:
#    path: ../firebase_analytics_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_analytics/firebase_analytics_platform_interface
      ref: SwineTech/bom_4.5.0-a
  firebase_analytics_web:
#    path: ../firebase_analytics_web
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_analytics/firebase_analytics_web
      ref: SwineTech/bom_4.5.0-a
  firebase_core:
#    path: ../../firebase_core/firebase_core
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: SwineTech/bom_4.5.0-a
  firebase_core_platform_interface:
#    path: ../../firebase_core/firebase_core_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: SwineTech/bom_4.5.0-a
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.analytics
        pluginClass: FlutterFirebaseAnalyticsPlugin
      ios:
        pluginClass: FirebaseAnalyticsPlugin
      macos:
        pluginClass: FirebaseAnalyticsPlugin
      web:
        default_package: firebase_analytics_web
