name: firebase_crashlytics
description:
  Flutter plugin for Firebase Crashlytics. It reports uncaught errors to the
  Firebase console.
version: 5.0.7-a
homepage: https://firebase.google.com/docs/crashlytics
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_crashlytics/firebase_crashlytics
topics:
  - firebase
  - crashlytics
  - errors
  - crashes

false_secrets:
  - example/**

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core:
#    path: ../../firebase_core/firebase_core
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: SwineTech/bom_4.8.0

  firebase_core_platform_interface:
#    path: ../../firebase_core/firebase_core_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: SwineTech/bom_4.8.0

  firebase_crashlytics_platform_interface:
#    path: ../firebase_crashlytics_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_crashlytics/firebase_crashlytics_platform_interface
      ref: SwineTech/bom_4.8.0

  flutter:
    sdk: flutter
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.crashlytics
        pluginClass: FlutterFirebaseCrashlyticsPlugin
      ios:
        pluginClass: FLTFirebaseCrashlyticsPlugin
      macos:
        pluginClass: FLTFirebaseCrashlyticsPlugin
