name: firebase_app_check_web
description: The web implementation of firebase_app_check
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_app_check/firebase_app_check_web
version: 0.2.2+2-a

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  _flutterfire_internals:
#    path: ../../_flutterfire_internals
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/_flutterfire_internals
      ref: SwineTech/bom_4.8.0

  firebase_app_check_platform_interface:
#    path: ../firebase_app_check_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_app_check/firebase_app_check_platform_interface
      ref: SwineTech/bom_4.8.0

  firebase_core:
#    path: ../../firebase_core/firebase_core
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: SwineTech/bom_4.8.0

  firebase_core_web:
#    path: ../../firebase_core/firebase_core_web
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_web
      ref: SwineTech/bom_4.8.0

  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.3
  firebase_core_platform_interface:
#    path: ../../firebase_core/firebase_core_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: SwineTech/bom_4.8.0

  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAppCheckWeb
        fileName: firebase_app_check_web.dart
