name: firebase_performance_web
description: Web implementation of Firebase Performance monitoring.
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_performance/firebase_performance_web
version: 0.1.7+15-a

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  _flutterfire_internals:
    #path: ../../_flutterfire_internals
        git:
          url: https://github.com/SwineTech-Inc/flutterfire.git
          path: packages/_flutterfire_internals
          ref: SwineTech/bom_3.13.1

  firebase_core:
    #path: ../../firebase_core/firebase_core
      git:
        url: https://github.com/SwineTech-Inc/flutterfire.git
        path: packages/firebase_core/firebase_core
        ref: SwineTech/bom_3.13.1

  firebase_core_web:
#    path: ../../firebase_core/firebase_core_web
      git:
        url: https://github.com/SwineTech-Inc/flutterfire.git
        path: packages/firebase_core/firebase_core_web
        ref: SwineTech/bom_3.13.1

  firebase_performance_platform_interface:
#    path: ../firebase_performance_platform_interface
      git:
        url: https://github.com/SwineTech-Inc/flutterfire.git
        path: packages/firebase_performance/firebase_performance_platform_interface
        ref: SwineTech/bom_3.13.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebasePerformanceWeb
        fileName: firebase_performance_web.dart
