name: firebase_app_installations_web
description: The web implementation of firebase_app_installations.
version: 0.1.6+15-a
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_app_installations/firebase_app_installations_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_app_installations/firebase_app_installations_web

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  _flutterfire_internals:
#    path: ../../_flutterfire_internals
      git:
        url: https://github.com/SwineTech-Inc/flutterfire.git
        path: packages/_flutterfire_internals
        ref: SwineTech/bom_3.13.1
  firebase_app_installations_platform_interface:
#    path: ../firebase_app_installations_platform_interface
      git:
        url: https://github.com/SwineTech-Inc/flutterfire.git
        path: packages/firebase_app_installations/firebase_app_installations_platform_interface
        ref: SwineTech/bom_3.13.1
  firebase_core:
#    path: ../../firebase_core/firebase_core
        git:
          url: https://github.com/SwineTech-Inc/flutterfire.git
          path: packages/firebase_core/firebase_core
          ref: SwineTech/bom_3.13.1
  firebase_core_web:
#    path: ../../firebase_core/firebase_core_web
      git:
        url: https://github.com/SwineTech-Inc/flutterfire.git
        path: packages/firebase_core/firebase_core_web
        ref: SwineTech/bom_3.13.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  firebase_core_platform_interface:
#    path: ../../firebase_core/firebase_core_platform_interface
      git:
        url: https://github.com/SwineTech-Inc/flutterfire.git
        path: packages/firebase_core/firebase_core_platform_interface
        ref: SwineTech/bom_3.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAppInstallationsWeb
        fileName: firebase_app_installations_web.dart
