name: cloud_firestore_web
description: The web implementation of cloud_firestore
homepage: https://github.com/firebase/flutterfire/tree/main/packages/cloud_firestore/cloud_firestore_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/cloud_firestore/cloud_firestore_web

version: 5.1.0-a

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  _flutterfire_internals:
#    path: ../../_flutterfire_internals
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/_flutterfire_internals
      ref: SwineTech/bom_4.5.0-a
  cloud_firestore_platform_interface:
#    path: ../cloud_firestore_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/cloud_firestore/cloud_firestore_platform_interface
      ref: SwineTech/bom_4.5.0-a
  collection: ^1.0.0
  firebase_core:
#    path: ../../firebase_core/firebase_core
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: SwineTech/bom_4.5.0-a
  firebase_core_web:
#    path: ../../firebase_core/firebase_core_web
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_web
      ref: SwineTech/bom_4.5.0-a
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  firebase_core_platform_interface:
#    path: ../../firebase_core/firebase_core_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: SwineTech/bom_4.5.0-a
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFirestoreWeb
        fileName: cloud_firestore_web.dart
