name: firebase_messaging_web
description: The web implementation of firebase_messaging
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_messaging/firebase_messaging_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_messaging/firebase_messaging_web
version: 4.1.2-a

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  _flutterfire_internals:
#    path: ../../_flutterfire_internals
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/_flutterfire_internals
      ref: SwineTech/bom_4.8.0

  firebase_core:
#    path: ../../firebase_core/firebase_core
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: SwineTech/bom_4.8.0

  firebase_core_web:
#    path: ../../firebase_core/firebase_core_web
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_web
      ref: SwineTech/bom_4.8.0

  firebase_messaging_platform_interface:
#    path: ../firebase_messaging_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_messaging/firebase_messaging_platform_interface
      ref: SwineTech/bom_4.8.0

  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.8.0
  web: ^1.0.0

dev_dependencies:
  firebase_core_platform_interface:
#    path: ../../firebase_core/firebase_core_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: SwineTech/bom_4.8.0

  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseMessagingWeb
        fileName: firebase_messaging_web.dart
